# -*- coding: utf-8 -*-
"""AAI551_Engg._Python_Final_Project_Priyanka_Shewale_10477984.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZ2KV2gu2KW7iWV8kD5xhSBwk-VGFLjT
"""

pip install emoji     #please install the emoji module

"""Name --> Priyanka Shewale
: Course -->  AAI 551 Engineering Programming: Python
: Assignment --> Final Project
"""

import numpy as np
import random                                                 ## POINT 1 ## # Random module imported to generate random number between the range
import emoji

Score_list = []
def esc(code):
    return f'\033[{code}m'
def attempt_count():                                         ## Function to count number of attempts made to guess the correct number
    if len(Score_list) <= 0:
        print("There is currently no high score, go for it !")
    else:
        print(emoji.emojize(":partying_face: The current high score is {} attempts :smiling_face_with_sunglasses:".format(min(Score_list))))  # High score value given for every range : High score is cleared off every time a new range is chosen
def Guess_game():
    print(emoji.emojize("Hello Master! :waving_hand: Welcome to the game of "+ esc('31;1;4') +"GUESSES!"+ esc(0)+ ":folded_hands:")) 
    player_name = input("Please enter your name ?--------------> ")                                                                                          # User Input
    wanna_play = input(emoji.emojize("Hi,{}  would you like to play the guessing game? :play_button:(Enter Yes/No):---------->  ".format(player_name)))  # User Input
    if wanna_play.lower()== "no":
      print(emoji.emojize(":smiling_face_with_smiling_eyes: That's cool, have a good one! :folded_hands:"))
    elif wanna_play.lower() == "yes":  
      attempts = 0
      attempt_count()
      range = input("Please enter the max number that you would like to play the Guess game ,starting from 1 to------------->  ")     ## POINT 2 ##    # Taking Max value from player to fix the range
      range = int(range)                                    ## string to int conversion
      random_number = int(random.randint(1, range))         ## POINT 1 ## Random module imported to generate random number between the range
      #print(random_number)
    w_play = wanna_play
    while w_play.lower() == "yes":                          
        try:
            guess = input(emoji.emojize("I am thinking :thought_balloon: of a number from 1 to {}, Take a guess.------------->".format(range)))        ## POINT 4 ## # User Input
            if int(guess) < 1 or int(guess) > range:
                raise ValueError(emoji.emojize("Value entered is out of range"+" :warning:"+ ". Please guess within the given range"))   ## POINT 3 ## # User Input
            if int(guess) == random_number:
                print(emoji.emojize("Nice! You got it! "":bullseye: "))
                attempts += 1
                Score_list.append(attempts)
                print(emoji.emojize("It took you {} attempts"":clapping_hands: ".format(attempts)))  ## POINT 6 ##  # Displaying the Player score
                attempt_count()
                play_again = input(emoji.emojize("Would you like to play again? :repeat_button:(Enter Yes/No)------------->"))  # User Input: whether to continue the game or not
                if play_again.lower() == "yes":
                  attempts = 0
                  attempt_count()
                  same_range = input(emoji.emojize("Would you like continue to play again with the same range 1 to {}? (Enter Yes/No). :warning: Note : Selecting a new range will clear off your current high score.--------->".format(range))) # User Input: whether to continue the game with same range as before  or different
                  if same_range.lower() == 'yes' :
                    random_number = int(random.randint(1, range))                                   # game continues with same range
                    #print("same range random no is",random_number)
                    
                  elif same_range.lower() == 'no' :                                                 # game continues with different range
                    attempts = 0
                    Score_list.clear()
                    attempt_count()
                    range = input("Please enter the max number that you would like to play the Guess game ,starting from 1 to------>") ## POINT 2 ## # Taking Max value from player to fix the range again
                    range = int(range)
                    random_number = int(random.randint(1, range))
                elif play_again.lower() == "no":
                    print(emoji.emojize(":smiling_face_with_smiling_eyes: That's cool, have a good one! :folded_hands:")) # Player exits
                    break
                    
            elif int(guess) > random_number:
                print(emoji.emojize("Your guess is higher" + " :slightly_frowning_face:"+ " Please guess again"))  ## POINT 5 ## #Player enters wrong guess, prompting the player to enter below the wrong guess
                attempts += 1
            elif int(guess) < random_number:
                print(emoji.emojize("Your guess is lower" + ":slightly_frowning_face:"+ " Please guess again"))   ## POINT 5 ## #Player enters wrong guess, prompting the player to enter above the wrong guess
                attempts += 1
        except ValueError as err:
            print(emoji.emojize(":warning: Oh no!, invalid value :cross_mark:. Try again..."+":alien:"))   ## POINT 3 ## # Invalid input from Player
            #print("({})".format(err))
    
if __name__ == '__main__':   # Run to play the Guess Game
    Guess_game()